import Head from "next/head";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce page filtering",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="64x64" />
        <title>Ecommerce page filtering</title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
